services:
  postgres:
    image: 'postgres:latest'
    restart: always
    container_name: my_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: test_db
    ports:
      - 127.0.0.1:5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ankurbsws@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local